author: "Tobe O <thosakwe@gmail.com>"
description: "New Dart runtime for ANTLR4."
homepage: "https://github.com/thosakwe/dart_antlr4"
name: "antlr4"
version: "1.0.0-dev"
dependencies: 
  charcode: "^1.1.1"
  string_scanner: "^1.0.1"
dev_dependencies: 
  test: "^0.12.16"
